// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = "https://gxrxrxivfzxgsrdyoovv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4cnhyeGl2Znp4Z3NyZHlvb3Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1MTU1NTgsImV4cCI6MjA1NjA5MTU1OH0.biMYtrxs-APxYFTcJxG80Aa-LvQYQdjOHuW1Le9oxJk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
