import axiosInstance from "./axiosInstance";

// GET /jobs/questions — fetch quiz questions; call once on mount and cache
export const _getJobsQuestions = () => axiosInstance.get("/jobs/questions");

// POST /jobs/recommend — submit quiz answers; returns { profileId, status: "processing" } immediately
// Use _getJobsRecommendations to poll until status === "ready"
export const _postJobsRecommend = (answers, force = false) =>
  axiosInstance.post("/jobs/recommend", { answers, force });

// GET /jobs/recommendations — poll after recommend; returns { profileId, status, jobs[], hasMore, total }
export const _getJobsRecommendations = (profileId, page = 0, limit = 10) =>
  axiosInstance.get("/jobs/recommendations", { params: { profileId, page, limit } });

// POST /jobs/interact — fire-and-forget tracking; action: 'saved'|'applied'|'interview'|'offer'|'dismissed'
export const _postJobsInteract = (profileId, jobId, action) => {
  if (!profileId || !jobId) return;
  axiosInstance
    .post("/jobs/interact", { profileId, jobId, action })
    .catch(() => {}); // intentional fire-and-forget — swallow silently
};

// GET /jobs/history — restore last recommendation session on page mount
export const _getJobsHistory = () => axiosInstance.get("/jobs/history");

// POST /jobs/more — trigger Lambda to fetch more jobs for existing profile
// Returns { status: "processing" } — poll _getJobsRecommendations for new results
export const _postJobsMore = (profileId) =>
  axiosInstance.post("/jobs/more", { profileId });

// POST /jobs/scout — Scout AI chat; returns { reply: string }
export const _postJobsScout = (profileId, jobId, message, history = []) =>
  axiosInstance.post("/jobs/scout", { profileId, jobId, message, history });

// POST /jobs/customize-resume — returns { customizedResume, changes[] }
export const _postJobsCustomizeResume = (jobId, profileId) =>
  axiosInstance.post("/jobs/customize-resume", { jobId, profileId });

// POST /jobs/cover-letter — returns { coverLetter: string }
export const _postJobsCoverLetter = (jobId, profileId) =>
  axiosInstance.post("/jobs/cover-letter", { jobId, profileId });

// POST /jobs/fit-analysis — returns { strengths[], gaps[], overallVerdict }
export const _postJobsFitAnalysis = (jobId, profileId) =>
  axiosInstance.post("/jobs/fit-analysis", { jobId, profileId });

// POST /jobs/interview-session — returns { sessionToken, maxDurationMs } for Anam AI mock interview
export const _postJobsInterviewSession = (jobId, profileId) =>
  axiosInstance.post("/jobs/interview-session", { jobId, profileId });

// DELETE /jobs/interview-session — release the global concurrency lock when interview ends
export const _deleteJobsInterviewSession = () =>
  axiosInstance.delete("/jobs/interview-session").catch(() => {});

// POST /jobs/interview-report — returns { report } generated by Gemini from the transcript
export const _postJobsInterviewReport = (jobId, profileId, transcript) =>
  axiosInstance.post("/jobs/interview-report", { jobId, profileId, transcript });

// POST /jobs/offer-decision — compare two offers with AI; returns { winner, analysis, regretNote, take }
export const _postJobsOfferDecision = (profileId, jobAId, jobBId, answers) =>
  axiosInstance.post('/jobs/offer-decision', { profileId, jobAId, jobBId, answers });

// POST /jobs/pipeline/reorder — persist custom card order within a stage
// column: 'saved'|'applied'|'interview'|'offer', jobIds: string[] (full ordered array)
export const _postJobsPipelineReorder = (profileId, column, jobIds) => {
  if (!profileId) return;
  axiosInstance
    .post('/jobs/pipeline/reorder', { profileId, column, jobIds })
    .catch(() => {}); // fire-and-forget
};

// GET /jobs/role-suggestions?q=... — fuzzy search over curated job titles (no auth required)
export const _getJobRoleSuggestions = (q) =>
  axiosInstance.get('/jobs/role-suggestions', { params: { q } });

// POST /jobs/add-manual — invoke Lambda to scrape LinkedIn URL and add job to Shortlisted
// Returns { status: 'processing', profileId }
export const _postJobsAddManual = (linkedinUrl, profileId) =>
  axiosInstance.post('/jobs/add-manual', { linkedinUrl, profileId });

export const _postJobsAddManualEntry = (fields, profileId) =>
  axiosInstance.post('/jobs/add-manual-entry', { ...fields, profileId });


