import axiosInstance from "./axiosInstance";

// GET /jobs/questions — fetch quiz questions; call once on mount and cache
export const _getJobsQuestions = () => axiosInstance.get("/jobs/questions");

// POST /jobs/recommend — submit quiz answers; returns { profileId, status: "processing" } immediately
// Use _getJobsRecommendations to poll until status === "ready"
export const _postJobsRecommend = (answers, force = false) =>
  axiosInstance.post("/jobs/recommend", { answers, force });

// GET /jobs/recommendations — poll after recommend; returns { profileId, status, jobs[], hasMore, total }
export const _getJobsRecommendations = (profileId, page = 0, limit = 10) =>
  axiosInstance.get("/jobs/recommendations", { params: { profileId, page, limit } });

// POST /jobs/interact — fire-and-forget tracking; action: 'saved'|'applied'|'interview'|'offer'|'dismissed'
export const _postJobsInteract = (profileId, jobId, action) => {
  if (!profileId || !jobId) return;
  axiosInstance
    .post("/jobs/interact", { profileId, jobId, action })
    .catch(() => {}); // intentional fire-and-forget — swallow silently
};

// GET /jobs/history — restore last recommendation session on page mount
export const _getJobsHistory = () => axiosInstance.get("/jobs/history");

// POST /jobs/more — trigger Lambda to fetch more jobs for existing profile
// Returns { status: "processing" } — poll _getJobsRecommendations for new results
export const _postJobsMore = (profileId) =>
  axiosInstance.post("/jobs/more", { profileId });

// POST /jobs/scout — Scout AI chat; returns { reply: string }
export const _postJobsScout = (profileId, jobId, message) =>
  axiosInstance.post("/jobs/scout", { profileId, jobId, message });

// POST /jobs/customize-resume — returns { customizedResume, changes[] }
export const _postJobsCustomizeResume = (jobId, profileId) =>
  axiosInstance.post("/jobs/customize-resume", { jobId, profileId });

// POST /jobs/cover-letter — returns { coverLetter: string }
export const _postJobsCoverLetter = (jobId, profileId) =>
  axiosInstance.post("/jobs/cover-letter", { jobId, profileId });

// POST /jobs/fit-analysis — returns { strengths[], gaps[], overallVerdict }
export const _postJobsFitAnalysis = (jobId, profileId) =>
  axiosInstance.post("/jobs/fit-analysis", { jobId, profileId });

// POST /jobs/interview-session — returns { sessionToken } for Anam AI mock interview
export const _postJobsInterviewSession = (jobId, profileId) =>
  axiosInstance.post("/jobs/interview-session", { jobId, profileId });

// POST /jobs/interview-report — returns { report } generated by Gemini from the transcript
export const _postJobsInterviewReport = (jobId, profileId, transcript) =>
  axiosInstance.post("/jobs/interview-report", { jobId, profileId, transcript });

// GET /jobs/credits — today's used/limit per action
export const _getJobCredits = () => axiosInstance.get('/jobs/credits');

// GET /jobs/role-suggestions?q=... — fuzzy search over curated job titles (no auth required)
export const _getJobRoleSuggestions = (q) =>
  axiosInstance.get('/jobs/role-suggestions', { params: { q } });
